=== actimem/blog/java/src/main/java/com/actimem/example/xml/examples/schema/company.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright 2015 BCN IT Consulting Ltd
  ~
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~     http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->

<xs:schema
        xmlns="http://www.actimem.com/company"
        targetNamespace="http://www.actimem.com/company"
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        elementFormDefault="qualified"
        attributeFormDefault="unqualified">
  <xs:element name="company" type="CompanyType"/>

  <xs:complexType name="CompanyType">
    <xs:sequence>
      <xs:element name="name" type="xs:string"/>
      <xs:element name="address" type="xs:string"/>
      <xs:element name="website" type="xs:anyURI"/>
      <xs:element name="workers">
        <xs:complexType>
          <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="employee" type="EmployeeType"/>
            <xs:element name="contractor" type="ContractorType"/>
            <xs:element name="visitor" type="VisitorType"/>
          </xs:choice>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="EmployeeType">
    <xs:sequence>
      <xs:element name="name" type="xs:string"/>
      <xs:element name="age" type="xs:integer"/>
      <xs:element name="join-date" type="xs:date"/>
      <xs:element name="department" type="DepartmentType"/>
      <xs:element name="contact" type="ContactType" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="comments" type="xs:string" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="employeeId" type="xs:string" use="optional"/>
  </xs:complexType>

  <xs:complexType name="ContractorType">
    <xs:sequence>
      <xs:element name="name" type="xs:string"/>
      <xs:element name="department" type="DepartmentType"/>
      <xs:element name="comments" type="xs:string" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="VisitorType">
    <xs:all>
      <xs:element name="title" type="xs:string"/>
      <xs:element name="name" type="xs:string"/>
      <xs:element name="expiry" type="xs:dateTime"/>
    </xs:all>
  </xs:complexType>

  <xs:complexType name="ContactType">
      <xs:attribute name="phone" type="xs:string" use="optional"/>
      <xs:attribute name="contact-type" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:simpleType name="DepartmentType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Accounts"/>
      <xs:enumeration value="IT"/>
      <xs:enumeration value="Sales"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="AgeType">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="0"/>
      <xs:maxInclusive value="150"/>
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== actimem/blog/java/src/main/java/com/actimem/example/xml/examples/schema/company.xml
<?xml version="1.0"?>

<!--
  ~ Copyright 2015 BCN IT Consulting Ltd
  ~
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~     http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->

<company xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.actimem.com/company company.xsd"
         xmlns="http://www.actimem.com/company">
    <name>Actimem</name>
    <address>135 Holborn Road, London, E1 5JK</address>
    <website>www.actimem.com</website>

    <workers>
        <employee employeeId="abc">
            <name>John Smith</name>
            <age>55</age>
            <join-date>2005-01-20</join-date>
            <department>Accounts</department>
            <contact phone="1111" contact-type="Home"/>
            <comments>He is the best director this
                        company has ever had</comments>
        </employee>
        <employee employeeId="3721">
            <name>James Lloyd</name>
            <age>23</age>
            <join-date>2012-10-05</join-date>
            <department>IT</department>
            <contact phone="2222" contact-type="Home"/>
            <contact phone="3333" contact-type="Work"/>
        </employee>
        <contractor>
            <name>Andy Grant</name>
            <department>Sales</department>
            <comments>
                <![CDATA[
                He is a rockie.
                We should <b>watch out</b> he gets the job done.
                ]]>
            </comments>
        </contractor>
        <visitor>
            <title>Mr</title>
            <name>Very Important Person</name>
            <expiry>2013-01-15T12:30:00</expiry>
        </visitor>
    </workers>
</company>
